load '../../build-support/dependencies.rb'

platform :ios, '11.0'
use_frameworks!

include_build_tools!

target 'AWSDataStoreCategoryPlugin' do
  pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "SQLite.swift", "~> 0.12.0"
  pod "AppSyncRealTimeClient", :git => 'https://github.com/aws-amplify/aws-appsync-realtime-client-ios.git', :branch => 'feat/data-race'

  target "AWSDataStoreCategoryPluginTests" do
    inherit! :complete
    
    include_test_utilities!
    pod 'AmplifyTestCommon', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
  end
end

target "HostApp" do
  use_frameworks!
  include_test_utilities!
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'
  pod "AWSMobileClient", $OPTIMISTIC_AWS_SDK_VERSION
  pod "AppSyncRealTimeClient", :git => 'https://github.com/aws-amplify/aws-appsync-realtime-client-ios.git', :branch => 'feat/data-race'

  target "AWSDataStoreCategoryPluginIntegrationTests" do
    inherit! :complete

    pod 'AmplifyPlugins/AWSAPIPlugin', :path => '../../'
  end

  target "AWSDataStoreCategoryPluginAuthIntegrationTests" do
    inherit! :complete

    pod 'AmplifyPlugins/AWSAPIPlugin', :path => '../../'
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
  end
end